### ISSUE TITLE
Seems not enough memory in task 'deepvariant_postprocess_variants' due to hard-coded runtime 'memory: "32 GB"' at GCP backend

### ISSUE THREAD

**Issue by LNGDingj** [PacificBiosciences/HiFi-human-WGS-WDL#112]
Hello @williamrowell , 

I would like to report an issue maybe caused by not enough memory in task 'deepvariant_postprocess_variants' due to hard-coded runtime 'memory: "32 GB"' at GCP, and need your helps to solve it, so I can complete the remaining analysis. Thanks so much!

Here is the background, please let me know if you need additional information 
Backend: GCP
Running platform: Terra
Analysis:  cohort analysis with 6 PacBio HiFi WGS samples
Issues: only 1 sample failed in procedure 'deepvariant_postprocess_variants' within task 'deepvariant'
![image](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/assets/53267778/481c18f9-8545-4fee-bb4b-82d330777db2)
-->
![image](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/assets/53267778/9e4dd881-6379-434d-9613-fe96f40b212b)

The last line in stderr of deepvariant_postprocess_variants is 
`2024-02-02 23:25:22.406845: I deepvariant/postprocess_variants.cc:103] Total #entries in single_site_calls = 14706242`

The task has failed in the VM when starting to run 'CVO sorting'. It is very likely due to not enough memory on requested VM, since the failed sample is with the largest 'Total #entries in single_site_calls' among all 6 samples

Here is the 'Total #entries in single_site_calls' of each sample
Total #entries in single_site_calls = **14706242** (failed in 'deepvariant->deepvariant_postprocess_variants')
Total #entries in single_site_calls = 14560422 (passed all tasks in humanwgs.sample_analysis) 
Total #entries in single_site_calls = 12107937 (passed all tasks in humanwgs.sample_analysis) 
Total #entries in single_site_calls = 12086854 (passed all tasks in humanwgs.sample_analysis) 
Total #entries in single_site_calls = 11375904 (passed all tasks in humanwgs.sample_analysis) 
Total #entries in single_site_calls = 11620281 (passed all tasks in humanwgs.sample_analysis) 

All other 5 samples successfully completed all tasks in humanwgs.sample_analysis
![image](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/assets/53267778/43c82a9e-a042-4395-aef4-d04b53096cce)

**Comment by williamrowell** [comment]
Hello,

We have also noticed that tasks executed in Terra tend to use more memory than tasks executed directly on GCP.  Terra must have some additional computational overhead on top of regular GCP task execution.  In the next release, I'll bump the memory for deepvariant_postprocess_variants to 40G and the memory for pbsv_discover to 10G.

Billy

**Comment by LNGDingj** [comment]
Hi @williamrowell ,
Thanks so much for the explanations. Could you give more advice on how I could continue with the current cohort analysis (described above) interrupted by one sample missing output from deepvariant_postprocess_variants? We need the results from cohort analysis for downstream experiment design. Thanks again!

**Comment by williamrowell** [comment]
Try [the `hotfix/terra-pbsv-memory-dockstore` branch](https://dockstore.org/workflows/github.com/PacificBiosciences/HiFi-human-WGS-WDL/HiFi-human-WGS-WDL:hotfix/terra-pbsv-memory-dockstore?tab=versions) if you need quick results.

I can't promise a specific timeline, but I'll also be increasing memory for these tasks in the next versioned release.

**Comment by LNGDingj** [comment]
Thanks a lot! With hotfix pipeline, task of deepvariant_postprocess_variants was completed for the sample needs more memory.
