### ISSUE TITLE
Where can I find the source code for multiple. py files used in sample-analysis.wdl and termary-analysis.wdl?

### ISSUE THREAD

**Issue by clhappyjiang** [PacificBiosciences/HiFi-human-WGS-WDL#126]
Hello!
       When I tried to run this process in HPC, I couldn't find some Python source code files, which caused the process to fail to run. The list is as follows:

Sample-analysis. wdl:

- extractoread length and quality. py
- check_trgtcoverage.py

Termary.analysis. wdl:

- parse_cohort.py
- yaml2ped.py
- calculate_phrank. py
- add_comphet_phase.py

Where can I find these Python files?

Thank you!

**Comment by williamrowell** [comment]
These scripts are all in the docker containers that are used for their tasks.  For example, `extract_read_length_and_qual.py` is used by the pbmm2 step.  In the ["Tool Versions and Docker Images"](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL?tab=readme-ov-file#tool-versions-and-docker-images) section of the README, you can find a link to the [Dockerfile](https://github.com/PacificBiosciences/wdl-dockerfiles/tree/3560fcc5a84e044067cea9c9a7669cfc2659178e/docker/pbmm2) for the pbmm2 step.  Any scripts are in the directory at this link.

There's no need to download these scripts individually if you are running the workflow.  They will be in the docker container already.
