### ISSUE TITLE
I validated main.wdl using womtool.jar and output a lot of WDL syntax error messages.

### ISSUE THREAD

**Issue by clhappyjiang** [PacificBiosciences/HiFi-human-WGS-WDL#128]
Hi
    My womtools-jar‘s version is 86. My runing command is：
![image](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/assets/34054649/bd9785cd-2100-47d1-823a-299227682a2a)
     After i ran the command，i found many error information that printed in the console ，just as pic show：
![image](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/assets/34054649/4ca68a42-0c19-4edf-b161-84ea36aa97d2)
     How can i fixed it？Or I can ignore this error information just run the main.wdl with Cromwell.jar?

**Comment by williamrowell** [comment]
Please email support@pacb.com.
