### ISSUE TITLE
How can miniwdl configure which queue to use for SLURM?

### ISSUE THREAD

**Issue by clhappyjiang** [PacificBiosciences/HiFi-human-WGS-WDL#130]
Hello!
Is it in the [slurm] tag of miniwdl.cfg?

**Comment by williamrowell** [comment]
Make sure the [miniwdl-slurm](https://github.com/miniwdl-ext/miniwdl-slurm) extension is installed and add a default runtime option for [`slurm_partition`](https://github.com/miniwdl-ext/miniwdl-slurm/blob/624ab390ea872082798733fefbb327dec99e2cde/src/miniwdl_slurm/__init__.py#L102) to your `miniwdl.cfg`.  You can see how to specify other runtime defaults at the link.

Example:

```ini
[task_runtime]
# Setting a 'maxRetries' default allows jobs that fail due to intermittent
# errors on the cluster to be retried.
## Requires miniwdl >= 1.9.0
command_shell = /bin/bash
defaults = {
        "maxRetries": 2,
        "docker": "ubuntu:20.04",
        "slurm_partition": "yourfavoritepartitionnamehere"
    }
```
