### ISSUE TITLE
Deepvariant files -bcftools stats

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/HiFi-human-WGS-WDL#132]
Hello,

I run the workflow in snakemake pipeline and I am not sure if I can post it here anymore. When I run process_sample.smk file for sample "0006-101"

I get this  error in the log file:
```

[W::bcf_sr_set_samples] The sample "0006-101" was not found in samples/0006-101/deepvariant/0006-101.GRCh38.deepvariant.vcf.gz, skipping
Unable to parse the samples: "0006-101"
```
I checked the permission of the folder but it looks fine.  There is also this file in the folder 0006-101.GRCh38.deepvariant.vcf.gz

Can someone help me figure this error

Thank you

**Comment by williamrowell** [comment]
https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake has been deprecated and is no longer supported.  Please reach out to support@pacb.com or your Field Applications Bioinformatics Scientist if you need help transitioning to https://github.com/PacificBiosciences/HiFi-human-WGS-WDL.
