### ISSUE TITLE
samtools_reset task?

### ISSUE THREAD

**Issue by hudja** [PacificBiosciences/HiFi-human-WGS-WDL#142]
Hello, this is probably not a bug, but in rc2 `samtools.wdl` I can see `samtools_reset` task which removes `HP,PS,PC,SA,mg,mc,mi,rm,fi,fp,ri,rp` tags from `bam` file, but I cannot see this task being called anywhere. Am I missing something?

Thank you!

**Comment by williamrowell** [comment]
The files in the wdl-common submodule contain tasks that are used by multiple workflows. Not all tasks are used by all workflows.
