### ISSUE TITLE
Network errors contacting Quay.io

### ISSUE THREAD

**Issue by Mo7ammedFarahat** [PacificBiosciences/HiFi-human-WGS-WDL#144]
[2024-08-02 00:10:37,03] [info] WorkflowManagerActor: Workflow 1d59a918-9c14-48eb-ab41-4954f086c5cb failed (during ExecutingWorkflowState): java.lang.RuntimeException: Unable to start job. 

Inside call-cpg_pileup/stderr.submit:

WARNING: Couldn't use cached digest for registry: Get "https://quay.io/v2/": dial tcp [2600:1f18:483:cf01:8e6a:c950:848:e19b]:443: connect: cannot assign requested address
WARNING: Falling back to direct digest.
FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://quay.io/pacbio/pb-cpg-tools@sha256:b95ff1c53bb16e53b8c24f0feaf625a4663973d80862518578437f44385f509b: Get "https://quay.io/v2/": dial tcp [2600:1f18:483:cf02:556a:c33d:2296:61e9]:443: connect: cannot assign requested address

Same for call-paraphase:

FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://quay.io/pacbio/paraphase@sha256:186dec5f6dabedf8c90fe381cd8f934d31fe74310175efee9ca4f603deac954d: Get "https://quay.io/v2/": dial tcp [2600:1f18:483:cf02:5c1c:7ce4:bb33:d2b5]:443: connect: cannot assign requested address

Same for call-coverage_dropouts

WARNING: Couldn't use cached digest for registry: Get "https://quay.io/v2/": dial tcp [2600:1f18:483:cf01:d775:5fe7:4c84:600d]:443: connect: cannot assign requested address
WARNING: Falling back to direct digest.
FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://quay.io/pacbio/trgt@sha256:8c9f236eb3422e79d7843ffd59e1cbd9b76774525f20d88cd68ca64eb63054eb: Get "https://quay.io/v2/": dial tcp [2600:1f18:483:cf02:5c1c:7ce4:bb33:d2b5]:443: connect: cannot assign requested address

Same for call-trgt:

WARNING: Couldn't use cached digest for registry: Get "https://quay.io/v2/": dial tcp [2600:1f18:483:cf00:d132:ff60:66a5:45f1]:443: connect: cannot assign requested address
WARNING: Falling back to direct digest.
FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://quay.io/pacbio/trgt@sha256:8c9f236eb3422e79d7843ffd59e1cbd9b76774525f20d88cd68ca64eb63054eb: Get "https://quay.io/v2/": dial tcp [2600:1f18:483:cf01:8e6a:c950:848:e19b]:443: connect: cannot assign requested address

**Comment by williamrowell** [comment]
These are network errors as Cromwell tries to connect to quay.io to fetch container images. It's possible that these are transient errors with quay.io.  Can you try again to see if the error goes away?

**Comment by Mo7ammedFarahat** [comment]
I have to run from the beginning?
May I know why it didn't try multiple time to connect?

**Comment by williamrowell** [comment]
If [call caching](http://www.software.broadinstitute.org/WDL/cromwell_features/CallCaching/) has been enabled and configured, starting again will reuse the output from previous executions.

> May I know why it didn't try multiple time to connect?

Like you, I'm a Cromwell user and not a Cromwell developer. This question is better-suited for the https://github.com/broadinstitute/cromwell repo or the Cromwell [community forums](https://github.com/broadinstitute/cromwell?tab=readme-ov-file#community).
