### ISSUE TITLE
Average genome coverage

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#145]
Does this stat exist? If not, would be useful to add.

**Comment by penhoorn** [comment]
I think you can find a mosdepth summary file in the haplotagged_bam_mosdepth_summary directory, which will contain the summary stat that you're looking for.

**Comment by williamrowell** [comment]
It's calculated by https://github.com/brentp/mosdepth, and you can find the summary at the bottom of `*.mosdepth.summary.txt`, [example](https://downloads.pacbcloud.com/public/revio/2022Q4/WGS-variant-pipeline-analysis/alignments/HG002.GRCh38.haplotagged.mosdepth.summary.txt):

```
chrom  length     bases        mean  min max
...
total  3099842888 100370221941 32.38 0   60270
```

In the next release, it will also be exported as a primary output stat:

https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/c06f6b90d52b166ba4691e91ec79e08e7d32acc8/docs/singleton.md?plain=1#L100
