### ISSUE TITLE
Duplicate IDs in pbsv.phased.vcf.gz

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#146]
Hi,
There are multiple different records (different variants on different chromosomes) with the same ID in the VCF ID column. Likely a bug.

**Comment by williamrowell** [comment]
This is an artifact of `pbsv call` parallelization.  To reduce the runtime, pbsv structural variant calling is split into 14 roughly equal chunks.  The IDs are only unique within each chunk.
