### ISSUE TITLE
Unreachable then clause

### ISSUE THREAD

**Issue by adthrasher** [PacificBiosciences/HiFi-human-WGS-WDL#149]
`reference` is a required parameter for this task, so the `else` clause is unreachable.

https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/1cf2b2e80024290d0ec1ea93b6a279ea2de519b0/workflows/sample_analysis/sample_analysis.wdl#L346

**Comment by williamrowell** [comment]
Thanks for reporting this.  v2 is a major re-structure, and this has been taken care of in that release.
