### ISSUE TITLE
write_ped_phrank

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#159]
Hi,
What is this in the input JSON?

write_ped_phrank

THanks

**Comment by williamrowell** [comment]
`write_ped_phrank` is not in the inputs.json files in this repo.

**Comment by gevro** [comment]
It is showing up when I configure v2.0.4 in terra via dockstore.
<img width="1726" alt="Screenshot 2024-11-16 at 10 25 39 PM" src="https://github.com/user-attachments/assets/30e4d149-5eb6-4756-8922-13848a086fd7">

Can you double check?

I also see this import line here:
https://dockstore.org/workflows/github.com/PacificBiosciences/HiFi-human-WGS-WDL/HiFi-human-WGS-WDL-family:v2.0.4-dockstore?tab=files&file=%2Fworkflows%2Ffamily.wdl

import "wdl-common/wdl/tasks/write_ped_phrank.wdl" as Write_ped_phrank

So I suspect it is being configured properly.

What should this parameter be set to?

**Comment by williamrowell** [comment]
This is an optional input for a single task called by the workflow. Terra should not be exposing this input to the end user. You do not need to provide this input. Leave it blank. If you do not leave it blank, the workflow may not function properly.

Please reach out to support@pacb.com if you have more questions about how to run the workflow.

**Comment by gevro** [comment]
Hi, I think best to post here because I think there is some bug. In Terra, it is trying to run this step of the pipeline even though the above parameter is not defined. 
<img width="1544" alt="Screenshot 2024-11-18 at 10 00 49 AM" src="https://github.com/user-attachments/assets/56dac53b-3675-4522-b277-172fe395fa1f">

**Comment by gevro** [comment]
And note, this keeps me from being able to get the results of the pipeline, because if one of the steps fails, none of the outputs are available for download. So I need to figure out why the write_ped_phrank step is running even though the below parameter was left blank:

<img width="2029" alt="Screenshot 2024-11-18 at 10 57 48 AM" src="https://github.com/user-attachments/assets/b5179720-afe9-4e24-9a47-a13af3ffd71d">

**Comment by gevro** [comment]
I think the bug might be here:
https://github.com/PacificBiosciences/wdl-common/blob/43a6091d21b85925dda0c901b475aa4bb406d759/wdl/tasks/write_ped_phrank.wdl

The above is imported by the family wdl. And then this defines a 'sex' parameter:
input {
    String id

    Family? family
    String? sex

    String phenotypes

    Float disk_size = 1

    RuntimeAttributes runtime_attributes
  }

But when the following main family wdl calls write_ped_phrank:
call Write_ped_phrank.write_ped_phrank {
      input:
        id                 = family.family_id,
        family             = family,
        phenotypes         = phenotypes,
        disk_size          = size(flatten(hifi_reads), "GB") + 10,
        runtime_attributes = default_runtime_attributes
    }

It doesn't define sex. So then Terra requires the user to define the sex parameter in the main inputs.

So probably a fix would be to change the main call to write_ped_phrank in the family wdl to pass the sex parameter to write_ped_phrank?

**Comment by williamrowell** [comment]
If you are running the `family.wdl` entrypoint, the `sex` input is not accessed.

I think this error is because `Float disk_size = 1` is the wrong type.  It should be `Int disk_size = 1`.  Will make this change today.

**Comment by gevro** [comment]
Sure. But in the main script here: https://dockstore.org/workflows/github.com/PacificBiosciences/HiFi-human-WGS-WDL/HiFi-human-WGS-WDL-family:v2.0.4-dockstore?tab=files&file=%2Fworkflows%2Ffamily.wdl

There is a call to write_ped_phrank that does not provide an input value for Sex.
```
  if (defined(tertiary_map_file)) {
    scatter (sample in family.samples) {
      Array[File] hifi_reads = sample.hifi_reads
    }

    call Write_ped_phrank.write_ped_phrank {
      input:
        id                 = family.family_id,
        family             = family,
        phenotypes         = phenotypes,
        disk_size          = size(flatten(hifi_reads), "GB") + 10,
        runtime_attributes = default_runtime_attributes
    }
```

So then when write_ped_phrank is loaded from here: https://github.com/PacificBiosciences/wdl-common/blob/43a6091d21b85925dda0c901b475aa4bb406d759/wdl/tasks/write_ped_phrank.wdl

It is missing a value for Sex, which is defined in the Input:
```
input {
    String id

    Family? family
    String? sex

    String phenotypes

    Float disk_size = 1

    RuntimeAttributes runtime_attributes
  }
```

So I think Terra then asks the user to provide a value for 'Sex', because it doesn't have a value for it.

In any case, I'll test whatever you update. If you could please also update it in the dockstore.
