### ISSUE TITLE
New v2 pipeline

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#161]
Hi,
In the new v2 pipeline, there is no option to turn off tertiary analysis. Does the pipeline still output the primary VCF calls *before* tertiary analysis is performed? Since we want the raw vcf files, as we use our own custom annotations and filter thresholds. We don't want only tertiary vcf files.

Thanks

**Comment by williamrowell** [comment]
> In the new v2 pipeline, there is no option to turn off tertiary analysis. 

From the [input documentation](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/main/docs/family.md#inputs) for the family.wdl workflow:

```
File?	tertiary_map_file	If omitted, tertiary analysis will be skipped.
```

> Does the pipeline still output the primary VCF calls before tertiary analysis is performed?

Yes, the unfiltered VCFs are output regardless of whether tertiary analysis runs.
