### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#162]
Hi,
Is there documentation of all the output files?

**Comment by gevro** [comment]
Nevermind I found it. Would be helpful I think to link to it from the main page.

**Comment by williamrowell** [comment]
> Nevermind I found it. Would be helpful I think to link to it from the main page.

From the [Workflow Inputs](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL#workflow-inputs) section in the README:

> Workflow inputs for each entrypoint are described in [singleton](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/main/docs/singleton.md) and [family](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/main/docs/family.md) documentation.

**Comment by bioinformaticsguy** [comment]
> Nevermind I found it. Would be helpful I think to link to it from the main page.

Hi can you please share the link of the documentation of all the output files may be? i am still unable to figureout where is the link.

**Comment by williamrowell** [comment]
There are basic descriptions of the outputs [here](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/main/docs/family.md#outputs).  For more detailed descriptions, it's best to look at the documentation for the individual tools.  Is there an output I can help you with?

**Comment by bioinformaticsguy** [comment]
I had a quick question about the output folder structure.

After running the pipeline, I get an output directory with a name like this:

```code
20250506_121608_humanwgs_family/
```

Inside this folder, there is:

One main out/ folder, and

Several call-* folders, and inside each of those, there is also an out/ folder.

I'm a bit confused about the difference between the main out/ folder and the smaller out/ folders inside the call-* folders.

Can you please explain:

- What is the purpose of the main out/ folder?
- What do the out/ folders inside call-* folders represent?
- Which one should I look at if I'm only interested in the final results (like the VCF file with variants)?

**Comment by williamrowell** [comment]
Our `pslivar` call hase two `family-expr` expressions (`dominant`, `recessive`) and one `sample-expr` expression (`comphet_side`).

https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/24c703dcc6ce8d808cd71cc97f24c3a532f02f07/workflows/tertiary/tertiary.wdl#L307-L309
https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/24c703dcc6ce8d808cd71cc97f24c3a532f02f07/workflows/tertiary/tertiary.wdl#L311-L314
https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/24c703dcc6ce8d808cd71cc97f24c3a532f02f07/workflows/tertiary/tertiary.wdl#L316-L320

When these expressions are true for a family/sample, an `INFO` annotation is added with the samples that satisfy the expression, e.g., `dominant=HG002;comphet_side=HG002`.

`dominant` and `recessive` are terminal annotations, meaning that we don't do anything else with them before reporting.  `comphet_side` is used by the downstream step `slivar compound-hets` to identify potential compound heterozygous combinations of variants in affected individuals.  The output of `slivar compound-hets` is a new VCF in which the `INFO` annotation `slivar_comphet` has been added only for variants that satisfy the criteria.

The [`slivar tsv`](https://github.com/brentp/slivar/wiki/tsv:-creating-a-spreadsheet-from-a-filtered-VCF) command only adds variants to the tsv if their `INFO` field has samples with `sample-field`s that are explicitly listed in the command call.  For the tsv you referenced, we only include variant records that were tagged with `dominant` or `recessive`.  The missing variants must have been only flagged with `comphet_side`.

https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/24c703dcc6ce8d808cd71cc97f24c3a532f02f07/workflows/tertiary/tertiary.wdl#L413-L414
