### ISSUE TITLE
Configuration when parents unknown

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#163]
Hi,
How do I configure the input json when there are no parents? Do I set the value to unquoted 'null' ?

https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/main/backends/gcp/family.gcp.inputs.json

{
  "humanwgs_family.family": {
    "family_id": "String",
    "samples": [
      {
        "sample_id": "String",
        "hifi_reads": [
          "File"
        ],
        "affected": "Boolean",
        "sex": "String? (optional, ['MALE', 'FEMALE', null])",
        "father_id": "String? (optional)",
        "mother_id": "String? (optional)"
      }
    ]
  }

**Comment by williamrowell** [comment]
You can use the unquoted `null`, or you can delete the key/value completely, as in:

```json
{
  "humanwgs_family.family": {
  "family_id": "HG002",
  "samples": [
    {
      "sample_id": "HG002",
      "hifi_reads": [
        "gs://path/to/my.bam"
      ],
      "affected": true,
      "sex": "MALE"
    }
  ]
}
```

Some backends handle `null` in unexpected ways, so I would suggest deleting the key/value pairs for unused optional entirely rather than setting `null`.

**Comment by gevro** [comment]
Do you know if terra handles unquoted null correctly?

**Comment by williamrowell** [comment]
I think it should be to use `null`, but I haven't tested this directly.

**Comment by gevro** [comment]
I can test it. But what should I look for when I test it to know if it worked?
