### ISSUE TITLE
ref_map bug

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#164]
Hi,
I'm getting this error with v2.0.4:

Failed to evaluate 'ref_map' (reason 1 of 1): Evaluating read_map(ref_map_file) failed: Failed to read_map("gs://pacbio-wdl/hifi-wdl-resources-v2p0p0-rc6/GRCh38.ref_map.v2p0p0-rc6.gcp.tsv") (reason 1 of 1): [Attempted 1 time(s)] - IOException: Could not read from gs://pacbio-wdl/hifi-wdl-resources-v2p0p0-rc6/GRCh38.ref_map.v2p0p0-rc6.gcp.tsv: 404 Not Found GET https://storage.googleapis.com/download/storage/v1/b/pacbio-wdl/o/hifi-wdl-resources-v2p0p0-rc6%2FGRCh38.ref_map.v2p0p0-rc6.gcp.tsv?alt=media&userProject=terra-a6717d5b No such object: pacbio-wdl/hifi-wdl-resources-v2p0p0-rc6/GRCh38.ref_map.v2p0p0-rc6.gcp.tsv

Note, this is via Terra.

**Comment by gevro** [comment]
I'm curious if this issue has a solution? Thanks

**Comment by williamrowell** [comment]
The paths have been updated in the input templates:
https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/main/backends/gcp/singleton.gcp.inputs.json
https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/main/backends/gcp/family.gcp.inputs.json
