### ISSUE TITLE
paraphase_vcfs question

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#165]
Hi,
In v2.0.4, why is paraphase_vcfs marked as an optional output?

Array[File?] 	paraphase_vcfs 	Paraphase VCFs 	Compressed as .tar.gz

Thanks

**Comment by williamrowell** [comment]
This output is set to optional to handle edge cases (such as testing with small subset BAMs) where the input BAM may be missing regions.  Setting optional output allows the task to complete.
