### ISSUE TITLE
Issue with zenodo download link to reference bundle

### ISSUE THREAD

**Issue by padraicc** [PacificBiosciences/HiFi-human-WGS-WDL#80]
There are a couple of typos in the link to the reference bundle on zenodo  in the backend HPC [README.md ](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/main/backends/hpc/README.md)

```bash
# download the reference data bundle
wget https://zenodo.org/record/8415406/files/wdl-humanwgs.v1.0.1.resources.tgz

# extract the reference data bundle and rename as dataset
tar -xzf wdl-humanwgs.v1.0.1.resources.tgz && mv static_resources dataset
```

The correct link should be 

```bash
# download the reference data bundle
wget https://zenodo.org/records/8415406/files/wdl-humanwgs.v1.0.2.resource.tgz

# extract the reference data bundle and rename as dataset
tar -xzf wdl-humanwgs.v1.0.2.resource.tgz && mv static_resources dataset
```

**Comment by williamrowell** [comment]
Sorry and thanks! Added to upcoming documentation patch.

**Comment by sholt6** [comment]
FYI, the updated version appears to still be incorrect.

In the README is:

`wget https://zenodo.org/record/8415406/files/wdl-humanwgs.v1.0.2.resources.tgz`

Whereas the correct URL is:

`wget https://zenodo.org/**records**/8415406/files/wdl-humanwgs.v1.0.2.**resource**.tgz`

'record' and 'resources' are incorrect.

**Comment by williamrowell** [comment]
https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/commit/f396217ac550d0bfcd0a5c85a9e36a0afd707d8c
