### ISSUE TITLE
Allow fq or fq.gz to pbmm2 align and correct the error message

### ISSUE THREAD

**Issue by looxon93** [PacificBiosciences/HiFi-human-WGS-WDL#81]
Hi, thanks for a great WDL, I like it very much. 

However, I had a sample with extension .fq. Tool pbmm2_align is failing because script: `extract_read_length_and_qual.py` failed because only: .fastq or .bam extensions are allowed. So I thought that even compressed fastq isn't allowed which isn't the case when I looked at the code. 

So I am suggesting to allow .fq or fq.gz as well and fix the error message to describe all allow formats, even compressed ones. 

Thanks,
Luka.

**Comment by williamrowell** [comment]
Hi Luka,

Thanks for your feedback!

Unaligned BAMs are the primary output of PacBio instruments.  In order for later steps in the workflow to make use of base modification and other rich tags that are only present in PacBio unaligned BAM format, we will only be support (uBAM) input in the near future.  If it's not possible to obtain the original uBAM, a less rich version can be generated from fastq by [samtools import](http://www.htslib.org/doc/samtools-import.html).  We don't test on this type of input, however, so there may be downstream problems.

Billy
