### ISSUE TITLE
environment configuration

### ISSUE THREAD

**Issue by crazysummerW** [PacificBiosciences/HiFi-human-WGS-WDL#97]
Hello, 
I would like to set up HiFi-human-WGS-WDL on a local server based on the information you've provided. What are the minimum server requirements if I want to perform trio analysis (i.e., analyze at least three samples simultaneously)? Are there any specific system requirements? Would you mind sharing your test environment configuration, if possible?

**Comment by williamrowell** [comment]
Hello, and thanks for your interest.  Please reach out to support@pacb.com for any questions about setup that aren't covered by the README.  Thanks.
